# Generated by Django 2.2.4 on 2019-10-28 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False,default=1)),
                ('title', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('TNcash', models.BooleanField()),
                ('TNcard', models.BooleanField()),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
