# Generated by Django 2.2.4 on 2019-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.IntegerField(default=1,auto_created=True,verbose_name='transaction_id'),
        ),
    ]
