# Generated by Django 2.2.4 on 2019-10-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0004_auto_20191029_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='id',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
